#version 300 es 
layout(location = 0) in float a_scale;
layout(location = 2) in float a_scaleTo;
layout(location = 1) in vec3 a_position;
layout(location = 3) in vec3 a_positionTo;

uniform float u_time;

out float v_scale;
out vec3 v_position;
void main() {
    v_scale = mix(a_scale, a_scaleTo, sin(u_time * 10.0f) * 0.5f + 0.5f);
    v_position = mix(a_position, a_positionTo, sin(u_time * 10.0f) * 0.5f + 0.5f);
}