#version 300 es 
layout(location = 0) in float a_scale;
layout(location = 1) in uvec4 a_color;
layout(location = 2) in vec3 a_position;

uniform mat4 u_model;
uniform mat4 u_projection;
uniform mat4 u_viewInverse;

flat out uvec4 v_color;
void main() {
    gl_Position = u_projection * u_viewInverse * u_model * vec4(a_position, 1.0f);
    gl_PointSize = a_scale;
    gl_Position.y += a_scale / 1024.0f;
    v_color = a_color;
}