#version 300 es
precision highp float;

in vec3 v_normal;

uniform vec4 u_pickColor;
uniform sampler2D u_texture;

uniform Light {
  vec3 u_lightDirection;
};
uniform Material {
  vec4 u_diffuse;
};

layout(location = 0) out vec4 o_color;
layout(location = 1) out vec4 o_pickColor;

void main() {
  vec3 normal = normalize(v_normal);
  float light = dot(u_lightDirection, normal) * .5f + .5f;
  o_color = vec4(u_diffuse.rgb * light, u_diffuse.a);
  o_pickColor = vec4(u_pickColor / 255.0f);
}
