#version 300 es
precision highp float;

in vec3 v_normal;

uniform vec4 u_diffuse;
uniform vec3 u_lightDirection;
uniform vec3 u_pickColor;
uniform sampler2D u_texture;

out vec4 outColor;

void main () {
  if (u_pickColor != vec3(0.0)) {
    outColor = vec4(u_pickColor, 1.0);
    return;
  }
  vec3 normal = normalize(v_normal);
  float light = dot(u_lightDirection, normal) * .5 + .5;
  outColor = vec4(u_diffuse.rgb * light, u_diffuse.a);
}
