#version 300 es
layout(location = 0) in vec4 a_position;
layout(location = 3) in vec3 a_normal;

uniform Model {
  mat4 u_world;
};
uniform Camera {
  mat4 u_viewInverse;
  mat4 u_projection;
};

out vec3 v_normal;
out vec3 v_position;

void main() {
  vec4 pos = u_world * a_position;
  mat4 viewProjection = u_projection * u_viewInverse;
  gl_Position = viewProjection * pos;
  v_normal = mat3(u_world) * a_normal;
  v_position = vec3(pos.xyz / pos.w);
}
