#version 300 es 
precision highp float;

in vec4 v_texcoord;
in vec4 v_color;
out vec4 color;
uniform sampler2D u_texture;
uniform float u_buffer;
uniform vec4 u_color;
uniform float u_gamma;

void main() {
    float dist = texture(u_texture, v_texcoord.xy).r;
    float alpha = smoothstep(u_buffer - u_gamma, u_buffer + u_gamma, dist);
    color = vec4((u_color * v_color).rgb, alpha * u_color.a * v_color.a);
}