#version 300 es 
precision highp float;

in vec4 v_texcoord;
in vec4 v_color;

layout(location = 0) out vec4 o_color;
layout(location = 1) out vec4 o_pickColor;
layout(location = 2) out vec4 o_reflect;

uniform samplerCube u_texture;

void main() {
        o_color = texture(u_texture, v_texcoord.xyz) * v_color;
        o_reflect = texture(u_texture, v_texcoord.xyz) * v_color;
        o_pickColor = texture(u_texture, v_texcoord.xyz) * v_color;
   
}