#version 300 es 
layout(location = 0) in vec4 a_position;
layout(location = 1) in vec4 a_color;
uniform mat4 u_projection;
uniform mat4 u_view;
out vec2 v_texcoord;
out vec4 v_color;

void main() { 
              // Multiply the position by the matrix. 
    gl_Position = u_projection * u_view * vec4(a_position.xy, 0, 1); 

              // Pass the texcoord to the fragment shader. 
    v_texcoord = a_position.zw;
    v_color = a_color;
}