#version 300 es 
layout(location = 0) in vec4 a_position;
layout(location = 1) in vec4 a_color;
layout(location = 2) in vec4 a_texcoord;


uniform ViewProjection {
    mat4 u_view;
    mat4 u_projection;
};

uniform mat4 u_world;

out vec4 v_texcoord;
out vec4 v_color;

void main() {
    gl_Position = u_projection * u_view * u_world * a_position;
    v_texcoord = a_texcoord;
    v_color = a_color;
}