#version 300 es
layout(location = 0) in vec3 a_position;
layout(location = 6) in vec3 a_barycentric;

uniform Camera {
  mat4 u_view;
  mat4 u_projection;
};

uniform Model {
  mat4 u_world;
};

out vec3 v_barycentric;

void main() {
  // const mat4 u_world = mat4(
  //   1, 0, 0, 0,
  //   0, 1, 0, 0,
  //   0, 0, 1, 0,
  //   0, 0, 0, 1
  // );
  gl_Position = u_projection * u_view * u_world * vec4(a_position, 1.0f);
  v_barycentric = a_barycentric;
}
